# IMPORTANT: All unit test files must begin with UT_*
Import('env')
clonedEnv = env.Clone()
# Specify source files to build
SOURCES = Glob('*.cpp')

ut_Libs = clonedEnv.StaticLibrary(target = 'ut',  source = SOURCES)
clonedEnv.Install('#/lib', ut_Libs)
clonedEnv.Alias('install', '#/lib')
